### ISSUE TITLE
Update docs 

### ISSUE THREAD

**Issue by sylvaiin** [Urigo/meteor-client-bundler#13]
Hello,
Don't know if I'm really at the good place to ask this.
I'm a little bit confused about this package.

Could someone explain the main differences of approach between
**(meteor-angular2)** AND **(meteor) / (angular2 + meteor-client-bundle)**

What about ?
- Subscriptions / Publications
- MiniMongo
- Meteor.methods
- Accounts / Atmosphere plugins
- Deployment
- Ease of maintaining apps

Thank you anybody to enlight this point
-- Sylvain

**Comment by DAB0mB** [comment]
@sylvaiin They are the same. There shouldn't be any special treatments when using `meteor-client-bundler`, only it is a bit more flexible because basically what it does, it strips out Meteor's backend making it much more independent to use with whatever front-end framework that you would like, like React Native and Native Script. Personally I like the `meteor-client-bundler` approach since I only like Meteor's backend and I don't like the rest of their stuff which you're obligated to use once using their platform. Hopefully this explanation was detailed enough, I will close this issue because I wanna prevent spamming of the issue section :-)
