### ISSUE TITLE
Question re login

### ISSUE THREAD

**Issue by kokokenada** [Urigo/meteor-client-bundler#24]
Apologies if there's a better place for asking questions.  I'm porting some code that uses Meteor.loginWithPassword which isn't defined in meteor-client.  I'm unsure if this is a configuration issue or if I need to login in a different way.  Any pointers much appreciated.

**Comment by DAB0mB** [comment]
Just run `meteor add accounts-password` (or whatever this is) in your meteor server, re-bundle the client and you're good to go. For some packages few adjustments are required inorder for them to work with ReactNative, but I don't think that auth packages should have any problem with it.

**Comment by kokokenada** [comment]
Thanks for the reply.  And adding 'accounts-password' to bundler config.json did add Meteor.loginWithPassword to the generated 'meteor-client.js'.  Thanks.  

Now, is there something special I need to get a connection?  The login does not return because I have no connection to the server.  (Server is running and web version is fine.)

**Comment by DAB0mB** [comment]
This is actually a ReactNative related issue, not a Meteor one. Try changing the URL from `localhost` to `0.0.0.0`, or you can just write your IP explicitly. Don't forget that the `localhost` of the phone is not the same `localhost` as your computer's. I'm closing this issue because it gets off-topic.
