### ISSUE TITLE
Q: why the "meteor" package need to be in externals? Don't they also need to be bundled together?

### ISSUE THREAD

**Issue by hatelove85911** [Urigo/meteor-client-bundler#38]
I'm trying to get my head around the sharing code on both client and server. In the blog, you mentioned to add one external configuration to webpack config file:
```
  externals: function (context, request, callback) {
    var match = request.match(/^meteor\/(.+)$/);
    var pack = match && match[1];
    if (pack) {
      callback(null, ‘Package[“‘ + pack + ‘“]’);
    }
  }
```

Does this mean that the meteor packages won't be bundled into the client bundle.js? then how the client can run without these code available in the browser?

**Comment by DAB0mB** [comment]
This is just an alias to Meteor packages, so they can be loaded like so:

```js
import { Mongo } from 'meteor/mongo';
```

The reason why we do this is because we use our own custom bundler rather than relying on Meteor's bundler, where this logic already exists. I'm closing this issue, since it's not really an issue. If you have further questions you can ask, but please don't open a new issue
